/root/etl_final_task/run_etl.sh: line 13: python: command not found
